"""
himikama/backend/chain/confidence.py
═══════════════════════════════════════════════════════════════
Phase 5 — Legal Confidence Layer
Himikama — Sri Lankan Fundamental Rights Legal AI

Responsibility:
    Applied after the reasoning chain completes or terminates.
    Scores the final output, applies deterministic rule-based
    flags, prepares evaluation metadata, and returns the mandatory
    legal disclaimer for the final user-facing output.

    This module contains NO LLM calls.
    It does not call ChromaDB.
    It does not perform legal reasoning.
    It only evaluates the structured results returned by steps.py
    and runner.py.

Inputs:
    step_results:
        Dict mapping step key → step result dict.
        Expected keys: "step_1" ... "step_10".

    articles_identified:
        Optional list of articles identified in Step 4.
        These are candidate articles, not final legal conclusions.
        If omitted, this module attempts to read them from:
            step_results["step_4"]["data"]["articles_identified"]

    final_answer:
        Optional Step 10 synthesis answer. If provided, this module
        returns final_answer_with_disclaimer.

Outputs:
    ConfidenceResult dataclass:
        confidence_level
        flags
        flag_details
        status
        disclaimer
        explanation
        final_answer_with_disclaimer
        evaluation

Status values:
    complete            → full chain completed
    time_barred         → Step 1 hard gate failed
    not_state_actor     → Step 2 hard gate failed
    chain_incomplete    → expected steps missing or Step 10 absent

Confidence scoring:
    Hard gate failures:
        Step 1 fail → status=time_barred, no confidence level
        Step 2 fail → status=not_state_actor, no confidence level

    Full chain completed:
        Start at high.
        Downgrade by one level for each downgrade flag:
            no_harm
            weak_precedent
            final_supported_inconsistent
            state_actor_uncertain
            chain_incomplete

        Informational only:
            low_coverage
            candidate_inconsistency

    Final levels:
        high   → no downgrade flags
        medium → one downgrade flag
        low    → two or more downgrade flags

Structured Assessment:
    This file reads Step 10 structured assessment if available:

        step_results["step_10"]["data"]["structured_assessment"]

    The confidence layer does not create or modify final article
    conclusions. It only records them in evaluation metadata.

Usage:
    from chain.confidence import apply_confidence_layer

    confidence = apply_confidence_layer(
        step_results=step_results,
        final_answer=step_results["step_10"]["answer"],
    )

    firestore_payload = confidence.to_dict()
═══════════════════════════════════════════════════════════════
"""

from __future__ import annotations

import logging
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────
# CONSTANTS
# ─────────────────────────────────────────────────────────────

MANDATORY_DISCLAIMER = (
    "This assessment has been generated by an AI system and does not "
    "constitute legal advice. It is intended solely to help you understand "
    "your situation before consulting a qualified attorney. The analysis is "
    "based on the information provided and a limited corpus of case law, and "
    "may not reflect the most recent judicial decisions. Please consult a "
    "licensed lawyer before taking any legal action."
)

# Articles with fewer than 10 cases in the current corpus.
# Update this set after every major corpus expansion and audit rerun.
LOW_COVERAGE_ARTICLES: set[str] = {
    "10",
    "12(4)",
    "126",
    "126(2)",
    "13(3)",
    "13(4)",
    "13(5)",
    "14(1)(b)",
    "14(1)(d)",
    "14(1)(e)",
    "14(1)(f)",
    "14(A)",
    "15(7)",
    "17",
    "4(d)",
    "79",
    "80(3)",
}

# Confidence levels
HIGH = "high"
MEDIUM = "medium"
LOW = "low"
NO_CONFIDENCE = ""

# Status values
STATUS_COMPLETE = "complete"
STATUS_TIME_BARRED = "time_barred"
STATUS_NOT_STATE_ACTOR = "not_state_actor"
STATUS_CHAIN_INCOMPLETE = "chain_incomplete"

# Structured assessment article statuses
ARTICLE_STATUS_SUPPORTED = "supported"
ARTICLE_STATUS_WEAK_OR_UNCERTAIN = "weak_or_uncertain"
ARTICLE_STATUS_REJECTED = "rejected"

# Flags that reduce confidence by one level each.
DOWNGRADE_FLAGS: set[str] = {
    "no_harm",
    "weak_precedent",
    "final_supported_inconsistent",
    "state_actor_uncertain",
    "chain_incomplete",
}

# Flags that are shown to the user/evaluator but do not reduce confidence.
INFORMATIONAL_FLAGS: set[str] = {
    "low_coverage",
    "candidate_inconsistency",
}

EXPECTED_COMPLETED_STEPS: tuple[str, ...] = (
    "step_1",
    "step_2",
    "step_3",
    "step_4",
    "step_5",
    "step_6",
    "step_7",
    "step_8",
    "step_9",
    "step_10",
)


# ─────────────────────────────────────────────────────────────
# RESULT TYPE
# ─────────────────────────────────────────────────────────────

@dataclass
class ConfidenceResult:
    """
    Output of the confidence layer.

    Attributes:
        confidence_level:
            "high" | "medium" | "low" | "".
            Empty when the chain terminated at a hard gate.

        flags:
            List of active machine-readable flags.

        flag_details:
            Dict containing detailed data for flags, useful for
            Flutter display and evaluation/debugging.

        status:
            complete | time_barred | not_state_actor | chain_incomplete.

        disclaimer:
            Mandatory legal disclaimer text.

        explanation:
            Plain-English explanation for the Flutter confidence card.

        final_answer_with_disclaimer:
            If final_answer is passed to apply_confidence_layer(), this
            contains the final synthesis plus the mandatory disclaimer.

        evaluation:
            Machine-readable evaluation metadata for later audit.
    """

    confidence_level: str = NO_CONFIDENCE
    flags: list[str] = field(default_factory=list)
    flag_details: dict[str, Any] = field(default_factory=dict)
    status: str = STATUS_COMPLETE
    disclaimer: str = MANDATORY_DISCLAIMER
    explanation: str = ""
    final_answer_with_disclaimer: str = ""
    evaluation: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """
        Convert result to a Firestore-friendly dict.
        """
        return asdict(self)


# ─────────────────────────────────────────────────────────────
# SAFE ACCESS HELPERS
# ─────────────────────────────────────────────────────────────

def _get_step(step_results: dict[str, Any], step_key: str) -> dict[str, Any]:
    """Return a step result dict or an empty dict."""
    step = step_results.get(step_key, {})
    return step if isinstance(step, dict) else {}


def _get_step_data(step_results: dict[str, Any], step_key: str) -> dict[str, Any]:
    """Return step['data'] safely."""
    data = _get_step(step_results, step_key).get("data", {})
    return data if isinstance(data, dict) else {}


def _step_exists(step_results: dict[str, Any], step_key: str) -> bool:
    """Check whether a step exists and is a dict."""
    return isinstance(step_results.get(step_key), dict)


def _step_passed(step_results: dict[str, Any], step_key: str) -> bool:
    """
    Read a step's passed field safely.

    Missing steps default to True so missing Step 2 does not get
    misclassified as not_state_actor. Chain completeness is checked
    separately.
    """
    step = _get_step(step_results, step_key)
    return bool(step.get("passed", True))


def _extract_articles_from_step_results(step_results: dict[str, Any]) -> list[str]:
    """
    Extract articles_identified from Step 4 if the caller did not
    provide articles_identified explicitly.

    These are candidate articles, not final Step 10 conclusions.
    """
    step_4_data = _get_step_data(step_results, "step_4")
    articles = step_4_data.get("articles_identified", [])
    if not isinstance(articles, list):
        return []
    return [str(article) for article in articles if article]


def _extract_structured_assessment(step_results: dict[str, Any]) -> dict[str, Any]:
    """
    Extract normalized Step 10 structured assessment if available.

    Preferred location:
        step_results["step_10"]["data"]["structured_assessment"]

    Returns an empty dict if Step 10 has not yet been upgraded.
    """
    step_10_data = _get_step_data(step_results, "step_10")
    structured = step_10_data.get("structured_assessment", {})
    return structured if isinstance(structured, dict) else {}


def _extract_final_potentially_violated_articles(
    structured_assessment: dict[str, Any],
) -> list[str]:
    """
    Extract final supported articles from structured assessment.
    """
    articles = structured_assessment.get("final_potentially_violated_articles", [])
    if not isinstance(articles, list):
        return []
    return _dedupe_preserve_order([str(article) for article in articles if article])


def _extract_final_weak_or_uncertain_articles(
    structured_assessment: dict[str, Any],
) -> list[str]:
    """
    Extract final weak or uncertain articles from structured assessment.
    """
    articles = structured_assessment.get("final_weak_or_uncertain_articles", [])
    if not isinstance(articles, list):
        return []
    return _dedupe_preserve_order([str(article) for article in articles if article])


def _extract_final_rejected_articles(
    structured_assessment: dict[str, Any],
) -> list[str]:
    """
    Extract final rejected articles from structured assessment.
    """
    articles = structured_assessment.get("final_rejected_articles", [])
    if not isinstance(articles, list):
        return []
    return _dedupe_preserve_order([str(article) for article in articles if article])


def _extract_structured_article_assessments(
    structured_assessment: dict[str, Any],
) -> list[dict[str, Any]]:
    """
    Extract per-article structured assessments.
    """
    assessments = structured_assessment.get("article_assessments", [])
    if not isinstance(assessments, list):
        return []
    return [
        assessment
        for assessment in assessments
        if isinstance(assessment, dict)
    ]


def _dedupe_preserve_order(items: list[str]) -> list[str]:
    """Deduplicate a list while preserving order."""
    seen: set[str] = set()
    output: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            output.append(item)
    return output


# ─────────────────────────────────────────────────────────────
# FLAG CHECKS
# ─────────────────────────────────────────────────────────────

def _check_time_barred(step_results: dict[str, Any]) -> bool:
    """Step 1 failed: timeliness hard gate."""
    return _step_exists(step_results, "step_1") and not _step_passed(
        step_results,
        "step_1",
    )


def _check_not_state_actor(step_results: dict[str, Any]) -> bool:
    """Step 2 failed: state actor hard gate."""
    return _step_exists(step_results, "step_2") and not _step_passed(
        step_results,
        "step_2",
    )


def _check_no_harm(step_results: dict[str, Any]) -> bool:
    """Step 6 found harm not established."""
    if not _step_exists(step_results, "step_6"):
        return False
    step_6_data = _get_step_data(step_results, "step_6")
    return step_6_data.get("harm_established") is False


def _check_weak_precedent(step_results: dict[str, Any]) -> bool:
    """
    Step 7 found no or very limited similar cases.

    Current rule:
        0 case IDs → weak precedent.

    Optional extension:
        If retrieval.py later returns similarity scores, this function
        can be upgraded to flag low-scoring matches as weak precedent.
    """
    if not _step_exists(step_results, "step_7"):
        return False

    step_7_data = _get_step_data(step_results, "step_7")
    case_ids = step_7_data.get("case_ids", [])

    if not isinstance(case_ids, list):
        return True

    return len(case_ids) == 0


def _check_inconsistent(step_results: dict[str, Any]) -> bool:
    """Step 9 flagged inconsistencies."""
    if not _step_exists(step_results, "step_9"):
        return False
    step_9_data = _get_step_data(step_results, "step_9")
    return bool(step_9_data.get("inconsistencies_found", False))


def _find_articles_with_negative_step9_mentions(
    step_results: dict[str, Any],
    articles: list[str],
) -> list[str]:
    """
    Find articles that Step 9 appears to criticize or mark as unsupported.

    This is intentionally conservative. It only links an inconsistency
    to an article when Step 9 mentions that article near negative
    support language. This prevents a rejected candidate article from
    lowering confidence in a separate, well-supported final article.
    """
    if not articles or not _step_exists(step_results, "step_9"):
        return []

    step_9_answer = str(_get_step(step_results, "step_9").get("answer", ""))
    if not step_9_answer.strip():
        return []

    lower_answer = step_9_answer.lower()

    negative_signals = [
        "does not support",
        "not supported",
        "unsupported",
        "not mentioned",
        "no support",
        "weak support",
        "limited support",
        "insufficient support",
        "contradict",
        "inconsistent",
        "mismatch",
        "conflict",
        "does not align",
        "not align",
        "not applicable",
        "not relevant",
    ]

    affected: list[str] = []

    for article in _dedupe_preserve_order([
        str(article).strip()
        for article in articles
        if str(article).strip()
    ]):
        article_lower = article.lower()
        start = 0

        while True:
            index = lower_answer.find(article_lower, start)
            if index == -1:
                break

            window_start = max(0, index - 450)
            window_end = min(len(lower_answer), index + len(article_lower) + 450)
            window = lower_answer[window_start:window_end]

            if any(signal in window for signal in negative_signals):
                affected.append(article)
                break

            start = index + len(article_lower)

    return _dedupe_preserve_order(affected)


def _check_final_supported_inconsistent(
    step_results: dict[str, Any],
    final_supported_articles: list[str],
) -> bool:
    """
    Return True only when Step 9 inconsistency appears to affect
    final supported articles.

    If structured final articles are unavailable, fall back to the
    legacy behavior and treat Step 9 inconsistency as confidence-
    reducing.
    """
    if not _check_inconsistent(step_results):
        return False

    if not final_supported_articles:
        return True

    affected_supported = _find_articles_with_negative_step9_mentions(
        step_results,
        final_supported_articles,
    )

    return bool(affected_supported)


def _build_inconsistency_details(
    step_results: dict[str, Any],
    *,
    final_supported_articles: list[str],
    final_weak_or_uncertain_articles: list[str],
    final_rejected_articles: list[str],
) -> dict[str, Any]:
    """
    Build detailed Step 9 inconsistency metadata.

    This helps distinguish true final-answer inconsistency from
    candidate-level inconsistency that Step 10 already handled by
    marking articles as weak_or_uncertain or rejected.
    """
    step_9_data = _get_step_data(step_results, "step_9")

    affected_supported = _find_articles_with_negative_step9_mentions(
        step_results,
        final_supported_articles,
    )
    affected_weak = _find_articles_with_negative_step9_mentions(
        step_results,
        final_weak_or_uncertain_articles,
    )
    affected_rejected = _find_articles_with_negative_step9_mentions(
        step_results,
        final_rejected_articles,
    )

    return {
        "consistent": step_9_data.get("consistent"),
        "inconsistencies_found": step_9_data.get("inconsistencies_found"),
        "final_supported_articles": final_supported_articles,
        "final_weak_or_uncertain_articles": final_weak_or_uncertain_articles,
        "final_rejected_articles": final_rejected_articles,
        "affected_supported_articles": affected_supported,
        "affected_weak_or_uncertain_articles": affected_weak,
        "affected_rejected_articles": affected_rejected,
    }


def _check_state_actor_uncertain(step_results: dict[str, Any]) -> bool:
    """
    Step 2 passed but remained uncertain.

    This is not a hard gate failure, but it should reduce confidence
    because state actor status is essential to a Fundamental Rights claim.
    """
    if not _step_exists(step_results, "step_2"):
        return False
    if not _step_passed(step_results, "step_2"):
        return False
    step_2_data = _get_step_data(step_results, "step_2")
    return bool(step_2_data.get("is_uncertain", False))


def _find_low_coverage_articles(articles_for_coverage_check: list[str]) -> list[str]:
    """
    Return articles that have low corpus coverage.

    Prefer final Step 10 supported/weak articles when available.
    Fall back to Step 4 candidate articles before Step 10 is upgraded.
    """
    return [
        article
        for article in _dedupe_preserve_order(articles_for_coverage_check)
        if article in LOW_COVERAGE_ARTICLES
    ]


def _find_missing_steps(step_results: dict[str, Any]) -> list[str]:
    """
    Return missing steps for a supposedly completed chain.

    This is only applied after hard gates have passed. If Step 1 or
    Step 2 failed, missing later steps are expected and not treated as
    chain_incomplete.
    """
    return [
        step_key
        for step_key in EXPECTED_COMPLETED_STEPS
        if not _step_exists(step_results, step_key)
    ]


# ─────────────────────────────────────────────────────────────
# SCORING
# ─────────────────────────────────────────────────────────────

def _score_confidence(flags: list[str]) -> str:
    """
    Determine confidence level from active flags.

    0 downgrade flags → high
    1 downgrade flag  → medium
    2+ downgrade flags → low
    """
    downgrade_count = sum(1 for flag in flags if flag in DOWNGRADE_FLAGS)

    if downgrade_count == 0:
        return HIGH
    if downgrade_count == 1:
        return MEDIUM
    return LOW


def _append_disclaimer(final_answer: str, disclaimer: str = MANDATORY_DISCLAIMER) -> str:
    """
    Append the mandatory disclaimer to the final answer.

    This helper prevents the disclaimer from being accidentally omitted
    in the final user-facing response.
    """
    final_answer = (final_answer or "").strip()
    if not final_answer:
        return f"DISCLAIMER:\n{disclaimer}"

    # Avoid appending twice if a caller already appended it.
    if disclaimer in final_answer:
        return final_answer

    return f"{final_answer}\n\nDISCLAIMER:\n{disclaimer}"


# ─────────────────────────────────────────────────────────────
# EXPLANATION BUILDER
# ─────────────────────────────────────────────────────────────

def _build_explanation(
    *,
    confidence_level: str,
    flags: list[str],
    flag_details: dict[str, Any],
    status: str,
) -> str:
    """
    Build a plain-English explanation for the Flutter confidence card.
    """
    if status == STATUS_TIME_BARRED:
        days_elapsed = flag_details.get("time_barred", {}).get("days_elapsed")
        if days_elapsed is not None:
            return (
                "This assessment could not be completed because the incident "
                f"appears to have occurred approximately {days_elapsed} days ago, "
                "which is outside the 30-day filing window for Fundamental "
                "Rights petitions."
            )
        return (
            "This assessment could not be completed because the incident "
            "appears to fall outside the 30-day filing window for Fundamental "
            "Rights petitions."
        )

    if status == STATUS_NOT_STATE_ACTOR:
        return (
            "This assessment could not be completed because the party involved "
            "does not appear to be a state authority or a person acting under "
            "state power. Fundamental Rights petitions generally require state "
            "action."
        )

    if status == STATUS_CHAIN_INCOMPLETE:
        missing_steps = flag_details.get("chain_incomplete", {}).get(
            "missing_steps",
            [],
        )
        return (
            "The assessment could not be fully completed because one or more "
            f"reasoning steps were missing: {', '.join(missing_steps)}. "
            "The available output should be treated as incomplete."
        )

    level_text = {
        HIGH: (
            "The analysis indicates a relatively strong confidence level. "
            "The hard gates were satisfied, harm appears to be established, "
            "similar precedent was found, and the cross-validation step did "
            "not flag major inconsistencies."
        ),
        MEDIUM: (
            "The analysis indicates a moderate confidence level. The basic "
            "requirements appear to be satisfied, but at least one important "
            "uncertainty may affect the strength of the assessment."
        ),
        LOW: (
            "The analysis indicates a low confidence level. Multiple issues "
            "or uncertainties were identified, so the assessment should be "
            "treated cautiously."
        ),
    }.get(confidence_level, "The assessment has been completed.")

    notes: list[str] = []

    if "state_actor_uncertain" in flags:
        notes.append(
            "The state actor requirement was not fully clear from the "
            "available facts."
        )

    if "no_harm" in flags:
        notes.append(
            "The available facts do not clearly establish tangible harm."
        )

    if "weak_precedent" in flags:
        notes.append(
            "No closely similar cases were identified in the corpus, limiting "
            "the strength of precedent comparison."
        )

    if "final_supported_inconsistent" in flags:
        affected_supported = flag_details.get(
            "final_supported_inconsistent",
            {},
        ).get("affected_supported_articles", [])
        if affected_supported:
            notes.append(
                "The cross-validation step raised concerns about final "
                "supported article(s): "
                f"{', '.join(affected_supported)}."
            )
        else:
            notes.append(
                "The cross-validation step raised concerns that may affect "
                "the final supported article conclusions."
            )

    if "candidate_inconsistency" in flags:
        notes.append(
            "The cross-validation step found inconsistency only in candidate "
            "article(s) that were later marked weak/uncertain or rejected, "
            "so this is treated as an informational caution rather than a "
            "direct downgrade of the final supported conclusion."
        )

    if "low_coverage" in flags:
        low_articles = flag_details.get("low_coverage", {}).get("articles", [])
        if low_articles:
            notes.append(
                "The following article(s) have limited coverage in the corpus: "
                f"{', '.join(low_articles)}."
            )
        else:
            notes.append(
                "One or more identified articles have limited coverage in the "
                "case corpus."
            )

    if notes:
        return level_text + " Notes: " + " ".join(notes)

    return level_text


# ─────────────────────────────────────────────────────────────
# EVALUATION METADATA
# ─────────────────────────────────────────────────────────────

def _build_evaluation_metadata(
    *,
    step_results: dict[str, Any],
    articles_identified: list[str],
    flags: list[str],
    flag_details: dict[str, Any],
    status: str,
    confidence_level: str,
) -> dict[str, Any]:
    """
    Build machine-readable metadata for history, debugging, and
    future evaluation dashboards.
    """
    step_7_data = _get_step_data(step_results, "step_7")
    step_9_data = _get_step_data(step_results, "step_9")
    step_6_data = _get_step_data(step_results, "step_6")
    step_2_data = _get_step_data(step_results, "step_2")

    structured_assessment = _extract_structured_assessment(step_results)
    final_potentially_violated_articles = (
        _extract_final_potentially_violated_articles(structured_assessment)
    )
    final_weak_or_uncertain_articles = (
        _extract_final_weak_or_uncertain_articles(structured_assessment)
    )
    final_rejected_articles = _extract_final_rejected_articles(
        structured_assessment
    )
    article_assessments = _extract_structured_article_assessments(
        structured_assessment
    )

    case_ids = step_7_data.get("case_ids", [])
    if not isinstance(case_ids, list):
        case_ids = []

    case_ids = _dedupe_preserve_order([
        str(case_id)
        for case_id in case_ids
        if case_id
    ])

    completed_steps = [
        step_key
        for step_key in EXPECTED_COMPLETED_STEPS
        if _step_exists(step_results, step_key)
    ]

    return {
        "evaluated_at": datetime.now(timezone.utc).isoformat(),
        "status": status,
        "confidence_level": confidence_level,
        "flags": flags,
        "flag_details": flag_details,

        # Candidate Step 4 articles.
        # These are useful for debugging and retrieval analysis,
        # but should not be used as the main final-answer metric.
        "articles_identified": articles_identified,

        # Final Step 10 structured conclusions.
        # These are the preferred fields for quantitative evaluation.
        "structured_assessment": structured_assessment,
        "final_potentially_violated_articles": (
            final_potentially_violated_articles
        ),
        "final_weak_or_uncertain_articles": final_weak_or_uncertain_articles,
        "final_rejected_articles": final_rejected_articles,
        "overall_assessment": structured_assessment.get(
            "overall_assessment",
            "",
        ),
        "precedent_alignment": structured_assessment.get(
            "precedent_alignment",
            "",
        ),
        "article_assessments": article_assessments,

        # Existing confidence/evaluation metadata.
        "low_coverage_articles": flag_details.get("low_coverage", {}).get(
            "articles",
            [],
        ),
        "similar_case_ids": case_ids,
        "similar_case_count": len(case_ids),
        "harm_established": step_6_data.get("harm_established"),
        "state_actor_uncertain": step_2_data.get("is_uncertain"),
        "cross_validation_consistent": step_9_data.get("consistent"),
        "inconsistencies_found": step_9_data.get("inconsistencies_found"),
        "completed_steps": completed_steps,
        "missing_steps": _find_missing_steps(step_results),
    }


# ─────────────────────────────────────────────────────────────
# MAIN PUBLIC FUNCTION
# ─────────────────────────────────────────────────────────────

def apply_confidence_layer(
    step_results: dict[str, Any],
    articles_identified: list[str] | None = None,
    final_answer: str | None = None,
) -> ConfidenceResult:
    """
    Apply Himikama's deterministic confidence layer.

    Args:
        step_results:
            Dict mapping step key → step result dict.

        articles_identified:
            Optional list of article numbers identified in Step 4.
            If omitted, this function extracts them from step_results.
            These are candidate articles, not final legal conclusions.

        final_answer:
            Optional Step 10 synthesis text. If provided, the returned
            ConfidenceResult includes final_answer_with_disclaimer.

    Returns:
        ConfidenceResult with confidence level, flags, explanation,
        disclaimer, optional final answer with disclaimer, and evaluation
        metadata.
    """
    if not isinstance(step_results, dict):
        raise TypeError("step_results must be a dict")

    articles = (
        [str(article) for article in articles_identified if article]
        if articles_identified is not None
        else _extract_articles_from_step_results(step_results)
    )
    articles = _dedupe_preserve_order(articles)

    structured_assessment = _extract_structured_assessment(step_results)
    final_potentially_violated_articles = (
        _extract_final_potentially_violated_articles(structured_assessment)
    )
    final_weak_or_uncertain_articles = (
        _extract_final_weak_or_uncertain_articles(structured_assessment)
    )
    final_rejected_articles = _extract_final_rejected_articles(
        structured_assessment
    )

    # Use final supported + weak articles for low-coverage warning when
    # available. Fall back to Step 4 candidate articles until Step 10
    # structured output is fully implemented.
    articles_for_coverage_check = (
        final_potentially_violated_articles + final_weak_or_uncertain_articles
    )
    if not articles_for_coverage_check:
        articles_for_coverage_check = articles

    result = ConfidenceResult()

    # ── Hard gate: Step 1 timeliness ─────────────────────────
    if _check_time_barred(step_results):
        step_1_data = _get_step_data(step_results, "step_1")
        result.status = STATUS_TIME_BARRED
        result.flags = ["time_barred"]
        result.flag_details = {
            "time_barred": {
                "days_elapsed": step_1_data.get("days_elapsed"),
                "incident_date": step_1_data.get("incident_date"),
                "reason": step_1_data.get("reason"),
            }
        }
        result.confidence_level = NO_CONFIDENCE
        result.explanation = _build_explanation(
            confidence_level=result.confidence_level,
            flags=result.flags,
            flag_details=result.flag_details,
            status=result.status,
        )
        result.final_answer_with_disclaimer = _append_disclaimer(final_answer or "")
        result.evaluation = _build_evaluation_metadata(
            step_results=step_results,
            articles_identified=articles,
            flags=result.flags,
            flag_details=result.flag_details,
            status=result.status,
            confidence_level=result.confidence_level,
        )
        logger.info("Confidence layer: status=time_barred")
        return result

    # ── Hard gate: Step 2 state actor ────────────────────────
    if _check_not_state_actor(step_results):
        step_2_data = _get_step_data(step_results, "step_2")
        result.status = STATUS_NOT_STATE_ACTOR
        result.flags = ["not_state_actor"]
        result.flag_details = {
            "not_state_actor": {
                "is_state_actor": step_2_data.get("is_state_actor"),
                "is_uncertain": step_2_data.get("is_uncertain"),
            }
        }
        result.confidence_level = NO_CONFIDENCE
        result.explanation = _build_explanation(
            confidence_level=result.confidence_level,
            flags=result.flags,
            flag_details=result.flag_details,
            status=result.status,
        )
        result.final_answer_with_disclaimer = _append_disclaimer(final_answer or "")
        result.evaluation = _build_evaluation_metadata(
            step_results=step_results,
            articles_identified=articles,
            flags=result.flags,
            flag_details=result.flag_details,
            status=result.status,
            confidence_level=result.confidence_level,
        )
        logger.info("Confidence layer: status=not_state_actor")
        return result

    # ── Completed-chain checks ───────────────────────────────
    flags: list[str] = []
    flag_details: dict[str, Any] = {}

    missing_steps = _find_missing_steps(step_results)
    if missing_steps:
        flags.append("chain_incomplete")
        flag_details["chain_incomplete"] = {
            "missing_steps": missing_steps,
        }

    if _check_state_actor_uncertain(step_results):
        flags.append("state_actor_uncertain")
        flag_details["state_actor_uncertain"] = {
            "reason": "Step 2 passed but returned is_uncertain=True.",
        }

    if _check_no_harm(step_results):
        flags.append("no_harm")
        flag_details["no_harm"] = {
            "harm_established": False,
        }

    if _check_weak_precedent(step_results):
        flags.append("weak_precedent")
        step_7_data = _get_step_data(step_results, "step_7")
        flag_details["weak_precedent"] = {
            "case_ids": step_7_data.get("case_ids", []),
            "reason": "No similar case IDs were selected in Step 7.",
        }

    if _check_inconsistent(step_results):
        inconsistency_details = _build_inconsistency_details(
            step_results,
            final_supported_articles=final_potentially_violated_articles,
            final_weak_or_uncertain_articles=final_weak_or_uncertain_articles,
            final_rejected_articles=final_rejected_articles,
        )

        if _check_final_supported_inconsistent(
            step_results,
            final_potentially_violated_articles,
        ):
            flags.append("final_supported_inconsistent")
            flag_details["final_supported_inconsistent"] = {
                **inconsistency_details,
                "reason": (
                    "Step 9 inconsistency appears to affect one or more "
                    "final supported article conclusions."
                ),
            }
        else:
            flags.append("candidate_inconsistency")
            flag_details["candidate_inconsistency"] = {
                **inconsistency_details,
                "reason": (
                    "Step 9 inconsistency appears limited to candidate "
                    "article(s) that Step 10 marked weak_or_uncertain or "
                    "rejected."
                ),
            }

    low_coverage_articles = _find_low_coverage_articles(
        articles_for_coverage_check
    )
    if low_coverage_articles:
        flags.append("low_coverage")
        flag_details["low_coverage"] = {
            "articles": low_coverage_articles,
            "reason": (
                "These final supported/weak article(s) have limited coverage "
                "in the corpus."
            ),
        }

    flags = _dedupe_preserve_order(flags)

    result.status = (
        STATUS_CHAIN_INCOMPLETE
        if "chain_incomplete" in flags
        else STATUS_COMPLETE
    )
    result.flags = flags
    result.flag_details = flag_details
    result.confidence_level = _score_confidence(flags)
    result.explanation = _build_explanation(
        confidence_level=result.confidence_level,
        flags=result.flags,
        flag_details=result.flag_details,
        status=result.status,
    )
    result.final_answer_with_disclaimer = _append_disclaimer(final_answer or "")
    result.evaluation = _build_evaluation_metadata(
        step_results=step_results,
        articles_identified=articles,
        flags=result.flags,
        flag_details=result.flag_details,
        status=result.status,
        confidence_level=result.confidence_level,
    )

    logger.info(
        "Confidence layer: status=%s, level=%s, flags=%s",
        result.status,
        result.confidence_level,
        result.flags,
    )

    return result


# ─────────────────────────────────────────────────────────────
# OPTIONAL PUBLIC HELPER
# ─────────────────────────────────────────────────────────────

def append_disclaimer(final_answer: str) -> str:
    """
    Public helper for callers that only need disclaimer appending.
    """
    return _append_disclaimer(final_answer)
